Repository EasyMicroservices/FileManager, pull requests merged in 2023-01, with the labels that each got.

#13 add amazonS3Object provider
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3ObjectProvider.cs
Labels: enhancement

#18 ci(CSharp): add test actions + push nuget action
  .github/workflows/dotnet-format-action.yml
  .github/workflows/dotnet-linux.yml
  .github/workflows/dotnet-macos.yml
  .github/workflows/dotnet-windows.yml
  .github/workflows/nuget-push-public.yml
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3ObjectProvider.cs
Labels: enhancement, DevOps

#19 refactor folders structure
  src/CSharp/EasyMicroservices.FileManager.sln
Labels: Refactor

#16 Add github templates.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#25 Add workflow for golang and rust.
  .github/workflows/golang.yml
  .github/workflows/rust.yml
Labels: enhancement

#22 Init golang and implement disk providers.
  .gitignore
  src/Golang/CHANGELOG.md
  src/Golang/disk/lib.go
  src/Golang/disk/lib_test.go
  src/Golang/go.mod
  src/Golang/go.sum
  src/Golang/lib.go
  src/Golang/models.go
  src/Golang/providers.go
Labels: enhancement

#33 Revert "Merge pull request #15 from sabababaei/develop"
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/dotnet-format-action.yml
  .github/workflows/dotnet-linux.yml
  .github/workflows/dotnet-macos.yml
  .github/workflows/dotnet-windows.yml
  .github/workflows/golang.yml
  .github/workflows/nuget-push-public.yml
  .github/workflows/rust.yml
  .gitignore
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3ObjectProvider.cs
  src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs.Tests/Providers/AzureStorageBlobsTest.cs
  src/CSharp/EasyMicroservices.FileManager.AzureStorageBlobs/Providers/AzureStorageBlobsProvider.cs
  src/CSharp/EasyMicroservices.FileManager.sln
  src/Golang/CHANGELOG.md
  src/Golang/disk/lib.go
  src/Golang/disk/lib_test.go
  src/Golang/go.mod
  src/Golang/go.sum
  src/Golang/lib.go
  src/Golang/models.go
  src/Golang/providers.go
Labels: Refactor

#37 Support for Laboratory Virtualize tests #36
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3BucketProvider.cs
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3ObjectProvider.cs
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3PathProvider.cs
  src/CSharp/EasyMicroservices.FileManager.Tests/EasyMicroservices.FileManager.Tests.csproj
  src/CSharp/EasyMicroservices.FileManager.Tests/Providers/FileProviders/AmazonS3FileProviderTest.cs
  src/CSharp/EasyMicroservices.FileManager.Tests/Providers/FileProviders/BaseFileProviderTest.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/PathProviders/BasePathProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/PathProviders/SystemPathProvider.cs
Labels: enhancement
