Repository EasyMicroservices/FileManager, pull requests merged in 2023-03, with the labels that each got.

#38 Implement sync methods in rust
  src/Rust/CHANGELOG.md
  src/Rust/src/disk/lib.rs
  src/Rust/src/disk/lib_test.rs
  src/Rust/src/lib.rs
  src/Rust/src/providers.rs
Labels: enhancement

#40 Add support for Cancellationtoken and more write and read file methods
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/EasyMicroservices.FileManager.AmazonS3.csproj
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3BucketProvider.cs
  src/CSharp/EasyMicroservices.FileManager.AmazonS3/Providers/AmazonS3ObjectProvider.cs
  src/CSharp/EasyMicroservices.FileManager/EasyMicroservices.FileManager.csproj
  src/CSharp/EasyMicroservices.FileManager/Interfaces/IDirectoryManagerProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Interfaces/IFileManagerProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/DirectoryProviders/BaseDirectoryProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/DirectoryProviders/DiskDirectoryProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/DirectoryProviders/MemoryDirectoryProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/BaseFileProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/DiskFileProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/MemoryFileProvider.cs
Labels: enhancement

#41 Add test cases for write aqnd read bytes and text and lines and fix bugs
  src/CSharp/EasyMicroservices.FileManager.Tests/Providers/FileProviders/AmazonS3FileProviderTest.cs
  src/CSharp/EasyMicroservices.FileManager.Tests/Providers/FileProviders/BaseFileProviderTest.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/BaseFileProvider.cs
Labels: bug, enhancement

#43 Fix WriteStreamToFileAsync in memory file manager
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/BaseFileProvider.cs
  src/CSharp/EasyMicroservices.FileManager/Providers/FileProviders/MemoryFileProvider.cs
Labels: bug
